"""Walker utilities: git-repo detection and pre-commit hook installation.

walk_and_process() and the parallel/_sequential processing methods remain on
CodeNormalizer for now because they share too much instance state to extract
cleanly in a single pass.  The module-level functions here (_is_in_git_repo,
install_git_hook) are self-contained and belong at this layer.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from typing import Optional

from loguru import logger


def _is_in_git_repo(path: Path) -> bool:
    """Return True if *path* is inside a git working tree."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            capture_output=True,
            text=True,
            cwd=str(path if path.is_dir() else path.parent),
        )
        return result.returncode == 0
    except Exception:
        return False


def install_git_hook(hook_type: str = "pre-commit") -> bool:
    """Write a pre-commit hook that runs the normalizer in dry-run mode.

    The hook is installed into ``.git/hooks/`` in the current working directory.
    The Python interpreter path is baked in at install time (not resolved at
    hook-run time) so the hook always uses the same venv that generated it.
    """
    git_dir = Path(".git")

    if not git_dir.exists():
        logger.error("[X] Not a git repository")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    hook_path = hooks_dir / hook_type

    # Point to the package's compatibility shim so the hook entry point is
    # stable even after the internal module layout changes.
    # __file__ = code_normalizer_pro/engine/walker.py
    # .parent   = code_normalizer_pro/engine/
    # .parent.parent = code_normalizer_pro/
    normalizer_script = Path(__file__).resolve().parent.parent / "code_normalizer_pro.py"

    hook_script = f"""#!/usr/bin/env python3
# Auto-generated by code_normalizer_pro.py
import subprocess
import sys
from pathlib import Path

def main():
    # Get staged Python files
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-only", "-z", "--diff-filter=ACM"],
        capture_output=True,
        text=True
    )

    files = [
        f for f in result.stdout.strip('\\0').split('\\0')
        if f.endswith('.py') and Path(f).exists()
    ]

    if not files:
        sys.exit(0)

    print(f"[?] Checking {{len(files)}} Python file(s)...")

    # Run normalizer in check mode, one file at a time. The CLI accepts a
    # single positional path, so passing all files at once breaks argparse.
    needs_normalization = []
    for file_path in files:
        result = subprocess.run(
            [{repr(sys.executable)}, {repr(str(normalizer_script))}, file_path, "--dry-run"],
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            print("\\n[X] Normalizer execution failed")
            if result.stderr.strip():
                print(result.stderr.strip())
            sys.exit(result.returncode)

        if "Would normalize:" in result.stdout:
            needs_normalization.append(file_path)

    if needs_normalization:
        print("\\n[!] Some files need normalization:")
        for file_path in needs_normalization:
            print(f" - {{file_path}}")
        print("\\nRun: uv run code-normalizer-pro <file> --in-place")
        print("Or add --no-verify to skip this check")
        sys.exit(1)

    print("[OK] All files are normalized")
    sys.exit(0)

if __name__ == "__main__":
    main()
"""

    hook_path.write_text(hook_script, encoding="utf-8", newline="\n")
    hook_path.chmod(0o755)

    logger.success(f"[OK] Installed {hook_type} hook at {hook_path}")
    logger.info("   Hook will check Python files before commit")
    logger.info("   Use 'git commit --no-verify' to skip check")
    return True
